/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.FlowLayout;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import jdk.nashorn.internal.runtime.JSONFunctions;
import run.Client;

/**
 *
 * @author Yan Kaic
 */
public class VClient extends javax.swing.JPanel {

  private static final Color ONLINE_COLOR = new Color(153, 255, 153);
  private static final Color OFFLINE_COLOR = new Color(224, 224, 224);
  private boolean available;
  private final Client client;

  /**
   * Creates new form VClient
   */
  public VClient() {
    initComponents();
    this.available = false;
    this.client = new Client("localhost", 3030);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup = new javax.swing.ButtonGroup();
    hostLabel = new javax.swing.JLabel();
    button_0x0 = new view.ColorButton();
    button_1x0 = new view.ColorButton();
    button_2x0 = new view.ColorButton();
    button_0x2 = new view.ColorButton();
    button_1x2 = new view.ColorButton();
    button_2x2 = new view.ColorButton();
    button_1x1 = new view.ColorButton();
    button_0x1 = new view.ColorButton();
    button_2x1 = new view.ColorButton();

    setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    hostLabel.setBackground(new java.awt.Color(224, 224, 224));
    hostLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    hostLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/host.png"))); // NOI18N
    hostLabel.setText("Host");
    hostLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    hostLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    hostLabel.setOpaque(true);
    hostLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    hostLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        hostLabelMouseClicked(evt);
      }
    });

    button_0x0.setText("0x0");
    buttonGroup.add(button_0x0);
    button_0x0.setName("0x0"); // NOI18N
    button_0x0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_1x0.setText("1x0");
    buttonGroup.add(button_1x0);
    button_1x0.setName("1x0"); // NOI18N
    button_1x0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_2x0.setText("2x0");
    buttonGroup.add(button_2x0);
    button_2x0.setName("2x0"); // NOI18N
    button_2x0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_0x2.setText("0x2");
    buttonGroup.add(button_0x2);
    button_0x2.setName("0x2"); // NOI18N
    button_0x2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_1x2.setText("1x2");
    buttonGroup.add(button_1x2);
    button_1x2.setName("1x2"); // NOI18N
    button_1x2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_2x2.setText("2x2");
    buttonGroup.add(button_2x2);
    button_2x2.setName("2x2"); // NOI18N
    button_2x2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_1x1.setText("1x1");
    buttonGroup.add(button_1x1);
    button_1x1.setName("1x1"); // NOI18N
    button_1x1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_0x1.setText("0x1");
    buttonGroup.add(button_0x1);
    button_0x1.setName("0x1"); // NOI18N
    button_0x1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    button_2x1.setText("2x1");
    buttonGroup.add(button_2x1);
    button_2x1.setName("2x0"); // NOI18N
    button_2x1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonEvent(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(hostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(button_0x0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_1x0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_2x0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(button_1x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_0x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_2x1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(button_0x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_1x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(button_2x2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(hostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(button_0x0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_1x0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_2x0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(button_0x1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(button_0x2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void hostLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostLabelMouseClicked
    alterAvailability();
  }//GEN-LAST:event_hostLabelMouseClicked

  private void alterAvailability() {
    if (available) {
      client.disconnect();
      setOffline();
    }
    else {
      try {
        client.connect();
        setText(client.getPort() + "");
        setOnline();
      }
      catch (IOException ex) {
        new Thread() {
          @Override
          public void run() {
            try {
              setOnline();
              sleep(100);
              setOffline();
            }
            catch (InterruptedException ex1) {
            }
          }
        }.start();
      }
    }
  }

  private void buttonEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEvent
    if (!client.isConnected()) {
      alterAvailability();
    }
    new Thread() {
      @Override
      public void run() {
        Color[][] array = getArray();
        client.send(array);
      }
    }.start();
  }//GEN-LAST:event_buttonEvent

  public void setOnline() {
    hostLabel.setBackground(ONLINE_COLOR);
    available = true;
  }

  public void setOffline() {
    hostLabel.setBackground(OFFLINE_COLOR);
    available = false;
  }

  public void setText(String text) {
    hostLabel.setText(text);
  }

  public String getText() {
    return hostLabel.getText();
  }

  public Color[][] getArray() {
    Enumeration<AbstractButton> buttons = buttonGroup.getElements();
    Color[][] array = new Color[3][3];
    while (buttons.hasMoreElements()) {
      AbstractButton button = buttons.nextElement();
      int i = Integer.parseInt(button.getName().charAt(0) + "");
      int j = Integer.parseInt(button.getName().charAt(2) + "");
      array[i][j] = button.getForeground();
    }
    return array;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup;
  private view.ColorButton button_0x0;
  private view.ColorButton button_0x1;
  private view.ColorButton button_0x2;
  private view.ColorButton button_1x0;
  private view.ColorButton button_1x1;
  private view.ColorButton button_1x2;
  private view.ColorButton button_2x0;
  private view.ColorButton button_2x1;
  private view.ColorButton button_2x2;
  private javax.swing.JLabel hostLabel;
  // End of variables declaration//GEN-END:variables

}
